### ISSUE TITLE
CFS and Default Fields

### ISSUE THREAD

**Issue by rcass** [redacademy/linc-winter-2018#10]
I notice there is quite a number of custom fields, some of which and kinda not necessary because the default field would be just fine.

For future reference, it is best to work with the WordPress defaults first (default WYSIWYG, featured image) before moving to a custom field for it.

**Okay things you should change:**

- [x] Testimonials: Instead of using a custom field for the image, just use the featured image field

**Things for future consideration:**

- [ ] Testimonials: Instead of creating a new text box, just use the default WYSIWYG. 

- [ ] Team Profiles: Instead of creating a new WYSIWYG for the bio, just use the default WYSIWYG.

**Comment by redsmi** [comment]
Changed testimonials custom field headshot to featured image
`<img src="<?php echo CFS() -> get ('image'); ?>">`
to
`<?php if ( has_post_thumbnail() ) : ?> <?php the_post_thumbnail('large', ['class' => 'testimonial-headshot', 'alt' => 'Testimonail headshot]); ?> <?php endif; ?>`

**Comment by rcass** [comment]
That code above looks great, I can't find where you have implemented those changes yet.  (I check on front-page.php and did not see the change)

On staging, I still see the CFS field for the image. Perhaps you just forgot to take it away on the staging site?

**Comment by rcass** [comment]
Ok, looks good 👍
