### ISSUE TITLE
Update Theme README.md

### ISSUE THREAD

**Issue by rcass** [redacademy/linc-winter-2018#12]
Most of the installation steps don't apply to your current theme.

Either remove the installation steps and just replace all that info with relevant information or remove the README.md entirely

**Comment by rcass** [comment]
Looks like you deleted the README.md, however there is still a readme.txt.  
It is just starter text, so update or delete this as well

**Comment by ghost** [comment]
File "readme.txt" renamed to "README.md" and updated.
