### ISSUE TITLE
Update plugin README.md

### ISSUE THREAD

**Issue by rcass** [redacademy/linc-winter-2018#13]
The title is fine, but the sentence below should be updated to match the project.

**Comment by ghost** [comment]
**Response:**
"LincEdge Functionality" plugin's README.md file has been updated to match the project description.

**Reference ID to commit:**
> https://github.com/redacademy/linc-winter-2018/commit/4fc8590ace9593c65697a842d781b1b59aea94b9

**Comment by rcass** [comment]
Looks good 👍
