### ISSUE TITLE
Form Issues

### ISSUE THREAD

**Issue by rcass** [redacademy/linc-winter-2018#17]
Here are a few thoughts after look at the forms:

- [x] Make some required fields. Currently a user can just click send with just their name and nothing else. Thing about what is the required info and set that in the gravity forms settings for that form.

- [ ] There seems to be many forms created in gravity forms, ask yourself, are ALL of these needed/necessary. The fewer there are the better it is for the client to manage

**Comment by calvintyvm** [comment]
Required fields are done, but the reason why there are 4 forms is because they are all 4 different forms. 2 for desktop (1 with message and 1 not) and 2 for mobile (1 with message and 1 not)

**Comment by calvintyvm** [comment]
Is this okay? Or is there a way I can shorten this I just dont know of.

**Comment by rcass** [comment]
So is the content on the forms different from desktop vs. mobile? As in different fields?

Most of the time one form does the trick and then you just apply css. But if the content is different, that is the only reason why you might need multiple forms.

If it just extra content not fields that are different, you could just hide (display:none) those paragraphs when necessary, rather than create a brand new form.

**Comment by rcass** [comment]
Or if you REALLY need all four, make the titles more clear to what they do. Add desktop or mobile to the title names

**Comment by calvintyvm** [comment]
added desktop and mobile
