### ISSUE TITLE
Confusing form Error Message

### ISSUE THREAD

**Issue by rcass** [redacademy/linc-winter-2018#2]
On the sign up form, next to the phone label it states 'optional' but then an error appears saying it is required. 
![screen shot 2018-03-22 at 9 55 00 am](https://user-images.githubusercontent.com/5028555/37785517-996647d0-2db7-11e8-8e96-1cb40424f953.png)
Just need to re-adjust your form settings

**Comment by calvintyvm** [comment]
Optional is removed and Phone is now a required field

**Comment by calvintyvm** [comment]
Added optional instead and made the others a required field
