### ISSUE TITLE
WP Ajax in Functions.php (why?)

### ISSUE THREAD

**Issue by rcass** [redacademy/linc-winter-2018#21]
Found this bit of code in your functions.php:
https://github.com/redacademy/linc-winter-2018/blob/7131b4cc5c2c0a180cd66ea3532ddf13d284c5ff/themes/linc-edge/functions.php#L86-L125

Wonderding:
1 - Why and what this is doing
2 - Is this necessary

It really was not clear why this is in here. Also if it is necessary, it should be in `inc/extras.php`

**Comment by calvintyvm** [comment]
1. What this is doing is enabling the button on mobile to be able to get the form and display it. Ive attached javascript to the button so that it also hides the title.

2. I guess this isnt necessary, I can just add another page on gravity forms and attach JS to that button via a html block.

**Comment by calvintyvm** [comment]
Added it in gravity forms, removed ajax in functions
