### ISSUE TITLE
Our Team Page: Accordion and plugins

### ISSUE THREAD

**Issue by rcass** [redacademy/linc-winter-2018#24]
I noticed you have a plugin for the accordion, honestly it is just overkill and kinda unnecessary.

Jim said he shared some code that is much simpler. Since the accordion is on the simpler side of things, there is really no need for the plugin and we want to to avoid having our theme be dependant on that plugin for such a simple thing.

So please work on removing this.

Hopefully it will remove the need for code like this: 
https://github.com/redacademy/linc-winter-2018/blob/ddb93fbd43ab2e2a27faab32d022d171357a0a4f/themes/linc-edge/about-team.php#L52-L57

Not a best practice to ref. short codes from an 3rd party plugin. Once again we are making out theme become dependant on that 3rd party plugin when we don't need it to be.

**Comment by redsmi** [comment]
https://github.com/redacademy/linc-winter-2018/commit/7297dc263e3ce17490dff2fc974af2c33dab909d

https://github.com/redacademy/linc-winter-2018/commit/577bb57dd8dbd748c8dc7a87e1a6670777109389
