### ISSUE TITLE
Footer.php and Widgetized Area

### ISSUE THREAD

**Issue by rcass** [redacademy/linc-winter-2018#26]
Looks like you are using the sidebar for the footer. This all well and good but you really need to change the labels to make it clear and not confusing to the user.
![screen shot 2018-03-22 at 2 35 16 pm](https://user-images.githubusercontent.com/5028555/37799904-60e652ac-2dde-11e8-80d1-ca88e049ba56.png)

It states side bar on the top but clearly feeds into the footer 😱 Very confusing!

**To do:**

- [x] Change the name of the widgetize area from `sidebar` to `footer`. This widgetized area is registered in the functions.php

- [x] Make sure the social media buttons are links

- [x] Privacy Policy should also be a link. Just use `href="#"` as a placeholder for now.

**Comment by calvintyvm** [comment]
finished, just need to deploy to see changes on site
