### ISSUE TITLE
Make index.php the default fallback, remove custom code

### ISSUE THREAD

**Issue by rcass** [redacademy/linc-winter-2018#27]
As with all WordPress sites, the index.php is the default for everything if a more appropriate template file  is not found.

Therefore, to make it an effective default there should be no custom code for the most part.
Right now the index.php looks more like a front-page.php 😱 

Please remove all that custom code and restore it to the default state.
You can copy and paste the code from the starter file:
https://github.com/redacademy/redstarter/blob/7ed6c862c4013a640c03db8b1d6af8d63dfbee48/index.php#L1-L40

If anything, the only real modification from this you would need to do is simply remove the call to the sidebar

**Comment by calvintyvm** [comment]
fixed

**Comment by rcass** [comment]
Looks good 👍
