### ISSUE TITLE
Remove many of the page templates

### ISSUE THREAD

**Issue by rcass** [redacademy/linc-winter-2018#28]
Right now, you have it that the client can select the different page templates
![screen shot 2018-03-22 at 2 43 47 pm](https://user-images.githubusercontent.com/5028555/37800282-8b2733dc-2ddf-11e8-8bc3-94669c533f10.png)

Given the design this really does not need to be.

I recommend removing these as page templates (removing the option of selecting them from the dropdown).

To do this simply remove this comment:
https://github.com/redacademy/linc-winter-2018/blob/ddb93fbd43ab2e2a27faab32d022d171357a0a4f/themes/linc-edge/price.php#L4

Instead you should have comments like this:
https://github.com/redacademy/linc-winter-2018/blob/ddb93fbd43ab2e2a27faab32d022d171357a0a4f/themes/linc-edge/archive.php#L2-L6

Make sure you are consistent with your php comments as well!

**Comment by calvintyvm** [comment]
fixed
