### ISSUE TITLE
front-page.php: Add links to App store

### ISSUE THREAD

**Issue by rcass** [redacademy/linc-winter-2018#31]
Just being forward thinking the client will prob want to add links to the two images on the front page to the app (in the app stores).

One way of making a link available, would be a custom field. That way they can change the link without having to go to the php

**Comment by calvintyvm** [comment]
Working on it

**Comment by rcass** [comment]
I am just re-opening this issue since this doesn't look resolved on the staging site. Let me know when the issue is visibly resolved on there and then this issue is closed 👌

**Comment by calvintyvm** [comment]
deployed
