### ISSUE TITLE
Mobile Header: Unable to see when logged in

### ISSUE THREAD

**Issue by rcass** [redacademy/linc-winter-2018#36]
![screen shot 2018-03-22 at 3 15 09 pm](https://user-images.githubusercontent.com/5028555/37801450-e85aea40-2de3-11e8-976b-248d3b25a98a.png)

The menu is hidden 😢

**Comment by redsmi** [comment]
Added 
`.admin-bar #masthead {
  top: 46px;
  @media screen and (min-width: 782px) {
    top: 32px;
  }
}`

WP menu default <600px is not position: fixed, leaving a gap above our menu (top: 46px) when we scroll down. Address this by adding
`@media screen and (max-width: 600px) {
  #wpadminbar {
      position: fixed !important;
  }
}`

**Comment by rcass** [comment]
Has this been deployed? I am not seeing the changes on the staging site?

**Comment by redsmi** [comment]
Right, it just wasn't deployed yet.

**Comment by rcass** [comment]
Oh okay I see it now!
