### ISSUE TITLE
redundant doc ready & window onload

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/linc-winter-2018#37]
Maybe there's a reason for using both doc ready and window.onload
however they both do almost the same thing so you can just use one e.g. doc ready instead of using both.

https://github.com/redacademy/linc-winter-2018/blob/657e87945d926ea4640239a92e86b9b26d10fe66/themes/linc-edge/js/about-team.js#L6

diff between doc.ready and window.onload

https://stackoverflow.com/questions/4584373/difference-between-window-load-and-document-ready-functions

**Comment by calvintyvm** [comment]
revmoed window.onload
