### ISSUE TITLE
IIFE & Doc ready

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/linc-winter-2018#38]
Since you are using both an IIFE for WordPress to work with jQuery and a doc ready declaration you could try the following instead...

jQuery(document).ready(function($){
   // the rest of your code goes here
});

https://github.com/redacademy/linc-winter-2018/blob/657e87945d926ea4640239a92e86b9b26d10fe66/themes/linc-edge/js/product.js#L1-L3

**Comment by calvintyvm** [comment]
Done, but just wondering why is this the better approach (compared to having jquery at the end)
