### ISSUE TITLE
Remove Development Plugins on Staging Site

### ISSUE THREAD

**Issue by rcass** [redacademy/linc-winter-2018#4]
Gentle reminder that development plugins (plugins only useful for the development process) should be on the local copies of the site not on the staging site.

The staging site should be as close and treated like a production website (live website).

So please remember to delete "show current template"

**Comment by calvintyvm** [comment]
Done.

**Comment by rcass** [comment]
Seems "show current template" is still on staging 🤔 

![devplugin](https://user-images.githubusercontent.com/5028555/37943024-a4afe5d0-312a-11e8-8aa1-cb7f354af29b.png)


Just close this issue once that plugin is removed (when you no longer need it)

**Comment by ghost** [comment]
Deleted.
