### ISSUE TITLE
move css in head to enqueue style

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/linc-winter-2018#40]
https://github.com/redacademy/linc-winter-2018/blob/657e87945d926ea4640239a92e86b9b26d10fe66/themes/linc-edge/header.php#L15

Flickity CSS is currently in the <head> of your header.php

Although this may work it's not the best way to add stylesheets with WordPress.
The better way is to enqueue the style in your functions.php file

**Comment by calvintyvm** [comment]
done
