### ISSUE TITLE
WP Reading Settings: Set Static Front Page & Post Page

### ISSUE THREAD

**Issue by rcass** [redacademy/linc-winter-2018#5]
Under the reading settings, just make it clear what the static front page & post page is set to.

Label the static page you are using for the front page as just 'front page' in the back end of WordPress

![screen shot 2018-03-22 at 10 06 11 am](https://user-images.githubusercontent.com/5028555/37786049-e52826ba-2db8-11e8-86da-ab1f5c0b17ea.png)

Even if you are not using posts at the moment, it is important to set this default for the client.

**Comment by calvintyvm** [comment]
added 
`if ( 'posts' == get_option( 'show_on_front' ) ) {
    include( get_home_template() );
} else {
    // Custom content markup goes here
}`
in front-page.php

A question, should we be using a title for front page? Right now we dont have a title as it is not needed for the page but we can add one and use css with `display:none` but I dont want to run in a situation where the client is stuck on why the front page title is not appearing in a case if she/he ever wanted to add one.

**Comment by rcass** [comment]
Looks like you resolved this, I remember talking to you about this.

Ya that bit of code is just not necessary.
