### ISSUE TITLE
Default Post Functionality

### ISSUE THREAD

**Issue by rcass** [redacademy/linc-winter-2018#6]
Currently it looks like the default functionality is not quite there, aka will look broken and unusable to the client.

Here are the things that need to be done:

- [x] In the reading settings (in the WordPress dashboard), set the the 'Post Page:' to the static page you have called 'Blog'. This will make the static blog page into the post index page (where all the posts are listed)

- [x] Style the 'blog' page once it is displaying all the posts

- [x] Style single post page. The functionality is there but needs style to actually be useable.

- [x] Style archive pages. This includes date, category, tag archive pages. Be sure to test that all of those pages look correct, so that it doesn't seem broken to the client.

**Comment by calvintyvm** [comment]
done

**Comment by rcass** [comment]
Good fixes 👍
