### ISSUE TITLE
Testimonial Single Template Page

### ISSUE THREAD

**Issue by rcass** [redacademy/linc-winter-2018#7]
This is minor, but I would make a single template file for the testimonial since when creating a new testimonial it is the link that is given to preview and right now it looks very broken.

Basically:

- [x] Create a single-testimonial.php  

- [x] Copy code from a similar template file as a starting point, maybe single.php.

- [x] Adjust code to match what you want pulled in for a single testimonial. Aka call your custom fields.

- [x] Style so it doesn't look broken.

Doesn't have to be anything fancy. Basically we are preventing the user from thinking the site is broken or unfinished by adding this template and style.

**Comment by redsmi** [comment]
https://github.com/redacademy/linc-winter-2018/commit/f02e4d19e8a9449e0d40a1b68a1da4cdc6a92421

**Comment by rcass** [comment]
Looks pretty good 👍
