### ISSUE TITLE
Team Profiles Single Template Page

### ISSUE THREAD

**Issue by rcass** [redacademy/linc-winter-2018#8]
Similar to this issue #7 

Basically:

- [x]  Create a single-team.php

- [x]  Copy code from a similar template file as a starting point, maybe single.php.

 Adjust code to match what you want pulled in for a single team member. Aka call your custom fields.

 Style so it doesn't look broken.

Doesn't have to be anything fancy. Basically we are preventing the user from thinking the site is broken or unfinished by adding this template and style.

**Comment by redsmi** [comment]
https://github.com/redacademy/linc-winter-2018/commit/15e0098231099a146934cf44a056f19e7d8c74e4

**Comment by rcass** [comment]
Looks great, I think it just needs some slight white space to the sides, I put it in a new ticket  #49
