### ISSUE TITLE
Consistent Coding Structure in post-types.php

### ISSUE THREAD

**Issue by rcass** [redacademy/linc-winter-2018#9]
In the functionality plugin, you have registered two post types.

Functionally they work, code wise there is room for improvement. Each post type, is written in a different 'style'. Be consistent and decide on one way to register your post types.

For the testimonial post-type, you assigned both arrays to variables, and then called them in the register_post_type function. 

Then for the team post-type, you only assigned one of the arrays to a variable and then wrote the second array within the register_post_type  function.

Just pick which style you want to use and adjust please 🙏 

- [x] Second (kinda minor, but better code quality): prefix the functions so they describe what they are doing. `testimonial_post_type()` and `team_post_type()`  are good, but better is `register_testimonial_post_type()` and `register_team_post_type`

- [x] On the team post type you included the translatable strings ( `_x(  )`) those really don't need to be there. Also you did not have them in the testimonials post type, so want to be consistent as well.

**Comment by redsmi** [comment]
https://github.com/redacademy/linc-winter-2018/commit/8fa50a026b12ca594565a2f10615398370342cfb
